spring:
  profiles:
    active: local

app:
  firebase:
    credentials: classpath:firebase-adminsdk.json
    credentials-json: ${FIREBASE_CREDENTIALS_JSON:}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:pokitdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false